theme: jekyll-theme-cayman
title: Hand Gesture Recognition Framework
description: Madan Raj Hari       Niveditha Hariharan         Muthunagappan Muthuraman
github:
  repository_url: https://github.com/muthu95/gesture-recognition