theme: jekyll-theme-cayman
title: Hand Gesture Recognition Framework
description: Madan Raj Hari       Niveditha Hariharan         Muthunagappan Muthuraman
url: https://github.com/muthu95/gesture-recognition
repository: https://github.com/MadanRaj-H/CS766-Project
